receivers:
  jaeger:
    protocols:
      thrift_compact:

processors:
  mpstmetadatatagging:
    roles:
      client:
        name: frontend
        messages:
          - Customer:
              name: "HTTP GET /customer"
          - FindNearest:
              name: "HTTP GET /driver.DriverService/FindNearest"
          - Route:
              name: "HTTP GET /route"
      driver:
        name: driver
        messages:
          - FindNearestResp:
              name: "HTTP GET /driver.DriverService/FindNearest"
      router:
        name: route
        messages:
          - Route:
              name: "HTTP GET /route"
      customer:
        name: customer
        messages:
          - CustomerResp:
              name: "HTTP GET /customer"
  mpstconformancemonitoring:
    semantic_model_type: gtype_pedro
    protocol_filename: twobuyer/TwoBuyer.scr
    protocol_name: TwoBuyer
    pedro_so_filename: ../Pedro/_build/default/src/pedrolib.so

exporters:
  logging:
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
      - jaeger
      processors:
      - mpstmetadatatagging
      - mpstconformancemonitoring
      exporters:
      - logging
      - jaeger
