receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080

processors:
  mpstconformancemonitoring:
    semantic_model_type: gtype_mixed_state
    protocol_sexp_filename: twobuttons/TwoButtons.sexp

exporters:
  logging:
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - mpstconformancemonitoring
      exporters:
      - logging
      - jaeger
