receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080

processors:

exporters:
  logging:
  mpstconformancemonitoring:
    semantic_model_type: gtype_mixed_state
    protocol_sexp_filename: twobuttons/TwoButtons.sexp

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      exporters:
      - logging
      - mpstconformancemonitoring
