receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080
  jaeger:
    protocols:
      thrift_compact:

processors:
  mpstconformancemonitoring:
    semantic_model_type: gtype_pedro
    protocol_filename: twobuyer/TwoBuyer.scr
    protocol_name: TwoBuyer
    pedro_so_filename: ../Pedro/_build/default/src/pedrolib.so

exporters:
  logging:
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:
      - otlp
      - jaeger
      processors:
        - mpstconformancemonitoring
      exporters:
      - logging
      - jaeger
