receivers:
  jaeger:
    protocols:
      thrift_compact:

processors:
  mpstmetadatatagging:
    roles:
      client:
        name: frontend
      driver:
        name: driver
      router:
        name: route
      customer:
        name: customer

exporters:
  logging:
  mpstconformancemonitoring:
    semantic_model_type: gtype_pedro
    protocol_filename: twobuyer/TwoBuyer.scr
    protocol_name: TwoBuyer
    pedro_so_filename: ../Pedro/_build/default/src/pedrolib.so

service:
  pipelines:
    traces:
      receivers:
      - jaeger
      processors:
      - mpstmetadatatagging
      exporters:
      - logging
      - mpstconformancemonitoring
