receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

processors:
  mpstconformancechecking:

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - mpstconformancechecking
      exporters:
      - logging
