receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

processors:
  groupbytrace:

exporters:
  logging:
  mpstconformancemonitoring:
    protocol: twobuyer/TwoBuyer_global_type.sexp

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - groupbytrace
      exporters:
      - logging
      - mpstconformancemonitoring
