receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080

processors:
  mpstconformancemonitoring:
    semantic_model_type: gtype_lts
    protocol_sexp_filename: twobuyer/TwoBuyer_global_type.sexp

exporters:
  logging:

service:
  pipelines:
    traces:
      receivers:
      - otlp
      processors:
      - mpstconformancemonitoring
      exporters:
      - logging
