// Code generated by "stringer -type=modelState"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NORMAL-0]
	_ = x[STUCK-1]
	_ = x[TERMINATED-2]
}

const _modelState_name = "NORMALSTUCKTERMINATED"

var _modelState_index = [...]uint8{0, 6, 11, 21}

func (i modelState) String() string {
	if i < 0 || i >= modelState(len(_modelState_index)-1) {
		return "modelState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _modelState_name[_modelState_index[i]:_modelState_index[i+1]]
}
