// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: globaltype.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action_ActionType int32

const (
	Action_SEND Action_ActionType = 0
	Action_RECV Action_ActionType = 1
)

// Enum value maps for Action_ActionType.
var (
	Action_ActionType_name = map[int32]string{
		0: "SEND",
		1: "RECV",
	}
	Action_ActionType_value = map[string]int32{
		"SEND": 0,
		"RECV": 1,
	}
)

func (x Action_ActionType) Enum() *Action_ActionType {
	p := new(Action_ActionType)
	*p = x
	return p
}

func (x Action_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_globaltype_proto_enumTypes[0].Descriptor()
}

func (Action_ActionType) Type() protoreflect.EnumType {
	return &file_globaltype_proto_enumTypes[0]
}

func (x Action_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action_ActionType.Descriptor instead.
func (Action_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_globaltype_proto_rawDescGZIP(), []int{0, 0}
}

type Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx           int32             `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Type          Action_ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=Action_ActionType" json:"type,omitempty"`
	FromRole      string            `protobuf:"bytes,3,opt,name=from_role,json=fromRole,proto3" json:"from_role,omitempty"`
	ToRole        string            `protobuf:"bytes,4,opt,name=to_role,json=toRole,proto3" json:"to_role,omitempty"`
	Continuations []*Action_Index   `protobuf:"bytes,5,rep,name=continuations,proto3" json:"continuations,omitempty"`
}

func (x *Action) Reset() {
	*x = Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globaltype_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_globaltype_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_globaltype_proto_rawDescGZIP(), []int{0}
}

func (x *Action) GetIdx() int32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *Action) GetType() Action_ActionType {
	if x != nil {
		return x.Type
	}
	return Action_SEND
}

func (x *Action) GetFromRole() string {
	if x != nil {
		return x.FromRole
	}
	return ""
}

func (x *Action) GetToRole() string {
	if x != nil {
		return x.ToRole
	}
	return ""
}

func (x *Action) GetContinuations() []*Action_Index {
	if x != nil {
		return x.Continuations
	}
	return nil
}

type GlobalType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start   int32     `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Actions []*Action `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *GlobalType) Reset() {
	*x = GlobalType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globaltype_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalType) ProtoMessage() {}

func (x *GlobalType) ProtoReflect() protoreflect.Message {
	mi := &file_globaltype_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalType.ProtoReflect.Descriptor instead.
func (*GlobalType) Descriptor() ([]byte, []int) {
	return file_globaltype_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalType) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GlobalType) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Action_Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Next  int32  `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *Action_Index) Reset() {
	*x = Action_Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_globaltype_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Action_Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action_Index) ProtoMessage() {}

func (x *Action_Index) ProtoReflect() protoreflect.Message {
	mi := &file_globaltype_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action_Index.ProtoReflect.Descriptor instead.
func (*Action_Index) Descriptor() ([]byte, []int) {
	return file_globaltype_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Action_Index) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Action_Index) GetNext() int32 {
	if x != nil {
		return x.Next
	}
	return 0
}

var File_globaltype_proto protoreflect.FileDescriptor

var file_globaltype_proto_rawDesc = []byte{
	0x0a, 0x10, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x82, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12,
	0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d,
	0x52, 0x6f, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x6f, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x33, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x1a, 0x31, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x6e, 0x65, 0x78, 0x74, 0x22, 0x20, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x52, 0x45, 0x43, 0x56, 0x10, 0x01, 0x22, 0x45, 0x0a, 0x0a, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x07, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_globaltype_proto_rawDescOnce sync.Once
	file_globaltype_proto_rawDescData = file_globaltype_proto_rawDesc
)

func file_globaltype_proto_rawDescGZIP() []byte {
	file_globaltype_proto_rawDescOnce.Do(func() {
		file_globaltype_proto_rawDescData = protoimpl.X.CompressGZIP(file_globaltype_proto_rawDescData)
	})
	return file_globaltype_proto_rawDescData
}

var file_globaltype_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_globaltype_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_globaltype_proto_goTypes = []interface{}{
	(Action_ActionType)(0), // 0: Action.ActionType
	(*Action)(nil),         // 1: Action
	(*GlobalType)(nil),     // 2: GlobalType
	(*Action_Index)(nil),   // 3: Action.Index
}
var file_globaltype_proto_depIdxs = []int32{
	0, // 0: Action.type:type_name -> Action.ActionType
	3, // 1: Action.continuations:type_name -> Action.Index
	1, // 2: GlobalType.actions:type_name -> Action
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_globaltype_proto_init() }
func file_globaltype_proto_init() {
	if File_globaltype_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_globaltype_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_globaltype_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_globaltype_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Action_Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_globaltype_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_globaltype_proto_goTypes,
		DependencyIndexes: file_globaltype_proto_depIdxs,
		EnumInfos:         file_globaltype_proto_enumTypes,
		MessageInfos:      file_globaltype_proto_msgTypes,
	}.Build()
	File_globaltype_proto = out.File
	file_globaltype_proto_rawDesc = nil
	file_globaltype_proto_goTypes = nil
	file_globaltype_proto_depIdxs = nil
}
