name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: ["twobuyer", "exporters/mpstconformancemonitoringexporter"]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: cd ${{ matrix.pkg }} && go mod download all

    - name: Build
      run: cd ${{ matrix.pkg }} && go build -v .

    - name: Test
      run: cd ${{ matrix.pkg }} && go test -v .
